name: CI/CD Docker to AWS EC2
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup a docker buildx
        uses: docker/setup-buildx-actions@v3

      - name: Login to Docker hub
        uses: docker/login-actions@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB.TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags:
            ${{ secrets.DOCKERHUB_USERNAME }}/devops-cicd-flask:latest

      - name: SSH to deploy into EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-cicd-flask:latest
            docker stop flask_app || true
            docker rm flask_app || true
            docker run -d --name flask_app -p 5000:5000 ${{ secrets.DOCKERHUB_USERNAME }}/devops-cicd-flask:latest            
            

        
